version: '3'
services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./:/yarilog-front
      # node_modukes は volumes 管理にしたいが typescript だとホスト側にも実態が無いと import エラーとかが editer で出てしまう
      # - node-modules-data:/yarilog-front/node_modules
    command: sh -c "yarn && sh"
    ports:
      - 3000:3000
    environment:
      HOST: 0.0.0.0
      baseApiUrl: 'http://docker.for.mac.host.internal:8080'
      # ubuntu の場合はこちらを使う
      # baseApiUrl: 'http://172.17.0.1:8080'
      baseBrouserApiUrl: 'http://localhost:8080'
    working_dir: /yarilog-front
# volumes:
  # node-modules-data:
