version: '3'
services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./:/yarilog-front
      - node-modules-data:/yarilog-front/node_modules
    command: yarn run dev
    ports:
      - 3000:3000
    environment:
      HOST: 0.0.0.0
    working_dir: /yarilog-front
volumes:
  node-modules-data:
